// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABYyWTQgcLb37xvglL6MfJQKLcoq2Wlzc',
    appId: '1:651133025567:web:13b4d6b4d78a906dd2c42a',
    messagingSenderId: '651133025567',
    projectId: 'weather-21208',
    authDomain: 'weather-21208.firebaseapp.com',
    databaseURL: 'https://weather-21208-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weather-21208.appspot.com',
    measurementId: 'G-J4HL7W9SZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcbC09_ID-stk1JVPX_OtWuw5ZppLaE-Y',
    appId: '1:651133025567:android:48f8c88383015825d2c42a',
    messagingSenderId: '651133025567',
    projectId: 'weather-21208',
    databaseURL: 'https://weather-21208-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weather-21208.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0A9l4y3rUwhylCqrqmkYSs8uL8Ip33M8',
    appId: '1:651133025567:ios:d914d2d1349d2fbad2c42a',
    messagingSenderId: '651133025567',
    projectId: 'weather-21208',
    databaseURL: 'https://weather-21208-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weather-21208.appspot.com',
    iosBundleId: 'com.example.weatherMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0A9l4y3rUwhylCqrqmkYSs8uL8Ip33M8',
    appId: '1:651133025567:ios:61a31de86d086eecd2c42a',
    messagingSenderId: '651133025567',
    projectId: 'weather-21208',
    databaseURL: 'https://weather-21208-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'weather-21208.appspot.com',
    iosBundleId: 'com.example.weatherMonitoring.RunnerTests',
  );
}
